/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lacamentohoraextra;

import br.com.lacamentohoraextra.DAO.ConexaoSQL;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author daviramos
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Administrador() {
        initComponents();
    }

    private void showApontamento(Class<?> apontamentoClass) {
        try {
            JPanel apontamentoPanel = (JPanel) apontamentoClass.getDeclaredConstructor().newInstance();
            apontamentoPanel.setSize(content.getWidth(), content.getHeight());
            apontamentoPanel.setLocation(0, 0);

            content.removeAll();
            content.add(apontamentoPanel, BorderLayout.CENTER);
            content.revalidate();
            content.repaint();
        }
        catch (InstantiationException
                | IllegalAccessException
                | NoSuchMethodException
                | InvocationTargetException ex) {
            Logger.getLogger(
                    Administrador.class.getName()).log(
                    Level.SEVERE,
                    ex.getMessage(),
                    ex);
            JOptionPane.showMessageDialog(
                    Administrador.this,
                    "Database connection failed: " + ex.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarBtnGroup = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        sidebarmenu = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnLancamento = new javax.swing.JButton();
        btnAprovacao = new javax.swing.JButton();
        btnProjeto = new javax.swing.JButton();
        btnCliente1 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 51, 51));
        setMinimumSize(new java.awt.Dimension(940, 600));
        setName("mainframe"); // NOI18N

        container.setBackground(new java.awt.Color(234, 238, 243));
        container.setMinimumSize(new java.awt.Dimension(940, 600));

        sidebarmenu.setBackground(new java.awt.Color(0, 51, 102));
        sidebarmenu.setForeground(new java.awt.Color(0, 51, 102));

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(153, 204, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setContentAreaFilled(false);

        btnLancamento.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnLancamento.setForeground(new java.awt.Color(153, 204, 255));
        btnLancamento.setText("Lançamentos");
        btnLancamento.setContentAreaFilled(false);

        btnAprovacao.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnAprovacao.setForeground(new java.awt.Color(153, 204, 255));
        btnAprovacao.setText("Aprovações");
        btnAprovacao.setContentAreaFilled(false);

        btnProjeto.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnProjeto.setForeground(new java.awt.Color(153, 204, 255));
        btnProjeto.setText("Projetos");
        btnProjeto.setContentAreaFilled(false);

        btnCliente1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnCliente1.setForeground(new java.awt.Color(153, 204, 255));
        btnCliente1.setText("Clientes");
        btnCliente1.setContentAreaFilled(false);

        btnSair.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(153, 204, 255));
        btnSair.setText("Sair");
        btnSair.setContentAreaFilled(false);

        javax.swing.GroupLayout sidebarmenuLayout = new javax.swing.GroupLayout(sidebarmenu);
        sidebarmenu.setLayout(sidebarmenuLayout);
        sidebarmenuLayout.setHorizontalGroup(
            sidebarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLancamento, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnAprovacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarmenuLayout.setVerticalGroup(
            sidebarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarmenuLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAprovacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(0, 51, 102));
        content.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        content.setMinimumSize(new java.awt.Dimension(764, 600));
        content.setPreferredSize(new java.awt.Dimension(764, 600));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(sidebarmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatIntelliJLaf.registerCustomDefaultsSource("br.com.lacamentohoraextra.styles");
        FlatIntelliJLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprovacao;
    private javax.swing.JButton btnCliente1;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLancamento;
    private javax.swing.JButton btnProjeto;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel container;
    private javax.swing.JPanel content;
    private javax.swing.ButtonGroup sidebarBtnGroup;
    private javax.swing.JPanel sidebarmenu;
    // End of variables declaration//GEN-END:variables
}
